Select idEXPERIENCIA_LABORAL, titulo_Puesto, empresa, pais, fechaInicio, fechaFinal, area, subArea, descripcionResponsabilidad, numeroPersonasCargo, EX_LAB_idPERSONA from bd_bolsatrabajo.experiencia_laboral
USE bd_bolsatrabajo;

insert into `experiencia_laboral`(`idEXPERIENCIA_LABORAL`,`titulo_Puesto`,`empresa`,`pais`,`fechaInicio`,`fechaFinal`,`area`,`subArea`,`descripcionResponsabilidad`,`numeroPersonasCargo`,`EX_LAB_idPERSONA`) values (1,'Analista Programador','GMD','Peru','01/03/2010','01/05/2012','Arquitectura','sistemas TI','JP',6,3);
insert into `experiencia_laboral`(`idEXPERIENCIA_LABORAL`,`titulo_Puesto`,`empresa`,`pais`,`fechaInicio`,`fechaFinal`,`area`,`subArea`,`descripcionResponsabilidad`,`numeroPersonasCargo`,`EX_LAB_idPERSONA`) values (2,'Jefe de Proyectos','Synopsis S.A','Peru','06/08/2012','01/10/2012','Arquitectura y Sistemas TI','Desarrollo','Analista Programador',0,4);
insert into `experiencia_laboral`(`idEXPERIENCIA_LABORAL`,`titulo_Puesto`,`empresa`,`pais`,`fechaInicio`,`fechaFinal`,`area`,`subArea`,`descripcionResponsabilidad`,`numeroPersonasCargo`,`EX_LAB_idPERSONA`) values (3,'Analista funcional','Teamsoft','Peru','01/05/2012','15/07/2012','Arquitectura y Sistemas TI','Desarrollo','Analista Programador',0,6);
insert into `experiencia_laboral`(`idEXPERIENCIA_LABORAL`,`titulo_Puesto`,`empresa`,`pais`,`fechaInicio`,`fechaFinal`,`area`,`subArea`,`descripcionResponsabilidad`,`numeroPersonasCargo`,`EX_LAB_idPERSONA`) values (4,'Arquitecto Web','Teamsoft','Peru','01/05/2012','15/07/2012','Arquitectura y Sistemas TI','Desarrollo','apoyo a requerimientos',0,1);
insert into `experiencia_laboral`(`idEXPERIENCIA_LABORAL`,`titulo_Puesto`,`empresa`,`pais`,`fechaInicio`,`fechaFinal`,`area`,`subArea`,`descripcionResponsabilidad`,`numeroPersonasCargo`,`EX_LAB_idPERSONA`) values (5,'Consultor Java','Teamsoft','Peru','01/05/2012','15/07/2012','Arquitectura y Sistemas TI','Desarrollo','apollo en desarrollo a los developers',0,7);
insert into `experiencia_laboral`(`idEXPERIENCIA_LABORAL`,`titulo_Puesto`,`empresa`,`pais`,`fechaInicio`,`fechaFinal`,`area`,`subArea`,`descripcionResponsabilidad`,`numeroPersonasCargo`,`EX_LAB_idPERSONA`) values (6,'Consultor Java','Teamsoft','Peru','01/05/2012','15/07/2012','Arquitectura y Sistemas TI','Desarrollo','apollo en desarrollo a los developers',0,7);
insert into `experiencia_laboral`(`idEXPERIENCIA_LABORAL`,`titulo_Puesto`,`empresa`,`pais`,`fechaInicio`,`fechaFinal`,`area`,`subArea`,`descripcionResponsabilidad`,`numeroPersonasCargo`,`EX_LAB_idPERSONA`) values (7,'Consultor Java','Teamsoft','Peru','01/05/2012','15/07/2012','Arquitectura y Sistemas TI','Desarrollo','apollo en desarrollo a los developers',0,7);
